/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUploadDataRouteImport } from './routes/_authenticated/upload-data'
import { Route as AuthenticatedRequisitionsRouteImport } from './routes/_authenticated/requisitions'
import { Route as AuthenticatedOffersRouteImport } from './routes/_authenticated/offers'
import { Route as AuthenticatedInterviewsRouteImport } from './routes/_authenticated/interviews'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCandidatesRouteImport } from './routes/_authenticated/candidates'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCandidatesIndexRouteImport } from './routes/_authenticated/candidates.index'
import { Route as AuthenticatedCandidatesCandidateIdRouteImport } from './routes/_authenticated/candidates.$candidateId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUploadDataRoute = AuthenticatedUploadDataRouteImport.update({
  id: '/upload-data',
  path: '/upload-data',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRequisitionsRoute =
  AuthenticatedRequisitionsRouteImport.update({
    id: '/requisitions',
    path: '/requisitions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOffersRoute = AuthenticatedOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterviewsRoute = AuthenticatedInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCandidatesRoute = AuthenticatedCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCandidatesIndexRoute =
  AuthenticatedCandidatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCandidatesRoute,
  } as any)
const AuthenticatedCandidatesCandidateIdRoute =
  AuthenticatedCandidatesCandidateIdRouteImport.update({
    id: '/$candidateId',
    path: '/$candidateId',
    getParentRoute: () => AuthenticatedCandidatesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/candidates': typeof AuthenticatedCandidatesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/interviews': typeof AuthenticatedInterviewsRoute
  '/offers': typeof AuthenticatedOffersRoute
  '/requisitions': typeof AuthenticatedRequisitionsRoute
  '/upload-data': typeof AuthenticatedUploadDataRoute
  '/candidates/$candidateId': typeof AuthenticatedCandidatesCandidateIdRoute
  '/candidates/': typeof AuthenticatedCandidatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/interviews': typeof AuthenticatedInterviewsRoute
  '/offers': typeof AuthenticatedOffersRoute
  '/requisitions': typeof AuthenticatedRequisitionsRoute
  '/upload-data': typeof AuthenticatedUploadDataRoute
  '/candidates/$candidateId': typeof AuthenticatedCandidatesCandidateIdRoute
  '/candidates': typeof AuthenticatedCandidatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/candidates': typeof AuthenticatedCandidatesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/interviews': typeof AuthenticatedInterviewsRoute
  '/_authenticated/offers': typeof AuthenticatedOffersRoute
  '/_authenticated/requisitions': typeof AuthenticatedRequisitionsRoute
  '/_authenticated/upload-data': typeof AuthenticatedUploadDataRoute
  '/_authenticated/candidates/$candidateId': typeof AuthenticatedCandidatesCandidateIdRoute
  '/_authenticated/candidates/': typeof AuthenticatedCandidatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/candidates'
    | '/dashboard'
    | '/interviews'
    | '/offers'
    | '/requisitions'
    | '/upload-data'
    | '/candidates/$candidateId'
    | '/candidates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/interviews'
    | '/offers'
    | '/requisitions'
    | '/upload-data'
    | '/candidates/$candidateId'
    | '/candidates'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/candidates'
    | '/_authenticated/dashboard'
    | '/_authenticated/interviews'
    | '/_authenticated/offers'
    | '/_authenticated/requisitions'
    | '/_authenticated/upload-data'
    | '/_authenticated/candidates/$candidateId'
    | '/_authenticated/candidates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upload-data': {
      id: '/_authenticated/upload-data'
      path: '/upload-data'
      fullPath: '/upload-data'
      preLoaderRoute: typeof AuthenticatedUploadDataRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requisitions': {
      id: '/_authenticated/requisitions'
      path: '/requisitions'
      fullPath: '/requisitions'
      preLoaderRoute: typeof AuthenticatedRequisitionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offers': {
      id: '/_authenticated/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AuthenticatedOffersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interviews': {
      id: '/_authenticated/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof AuthenticatedInterviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidates': {
      id: '/_authenticated/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof AuthenticatedCandidatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidates/': {
      id: '/_authenticated/candidates/'
      path: '/'
      fullPath: '/candidates/'
      preLoaderRoute: typeof AuthenticatedCandidatesIndexRouteImport
      parentRoute: typeof AuthenticatedCandidatesRoute
    }
    '/_authenticated/candidates/$candidateId': {
      id: '/_authenticated/candidates/$candidateId'
      path: '/$candidateId'
      fullPath: '/candidates/$candidateId'
      preLoaderRoute: typeof AuthenticatedCandidatesCandidateIdRouteImport
      parentRoute: typeof AuthenticatedCandidatesRoute
    }
  }
}

interface AuthenticatedCandidatesRouteChildren {
  AuthenticatedCandidatesCandidateIdRoute: typeof AuthenticatedCandidatesCandidateIdRoute
  AuthenticatedCandidatesIndexRoute: typeof AuthenticatedCandidatesIndexRoute
}

const AuthenticatedCandidatesRouteChildren: AuthenticatedCandidatesRouteChildren =
  {
    AuthenticatedCandidatesCandidateIdRoute:
      AuthenticatedCandidatesCandidateIdRoute,
    AuthenticatedCandidatesIndexRoute: AuthenticatedCandidatesIndexRoute,
  }

const AuthenticatedCandidatesRouteWithChildren =
  AuthenticatedCandidatesRoute._addFileChildren(
    AuthenticatedCandidatesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCandidatesRoute: typeof AuthenticatedCandidatesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInterviewsRoute: typeof AuthenticatedInterviewsRoute
  AuthenticatedOffersRoute: typeof AuthenticatedOffersRoute
  AuthenticatedRequisitionsRoute: typeof AuthenticatedRequisitionsRoute
  AuthenticatedUploadDataRoute: typeof AuthenticatedUploadDataRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCandidatesRoute: AuthenticatedCandidatesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInterviewsRoute: AuthenticatedInterviewsRoute,
  AuthenticatedOffersRoute: AuthenticatedOffersRoute,
  AuthenticatedRequisitionsRoute: AuthenticatedRequisitionsRoute,
  AuthenticatedUploadDataRoute: AuthenticatedUploadDataRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
